version: "3.9"
services:
    voting:
        restart: unless-stopped
        build:
            context: .
        networks:
            - voting
        depends_on:
            - redis
        environment:
            - RUST_LOG=info
            - API_REDIS_HOST=redis
    redis:
        image: redis:alpine
        restart: unless-stopped
        networks:
            - voting

networks:
    voting:
